service: metadata-archive-api

frameworkVersion: '3'

custom:
  settings:
    METADATA_TABLE: metadata
    STUDY_TABLE: study
    SERIES_TABLE: series

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${self:custom.settings}
  region: ap-south-1
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:List*
          - dynamodb:Get*
          - dynamodb:Delete*
          - dynamodb:Update*
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchDeleteItem
          - s3:PutObject
          - s3:GetObject
        Resource:
          - "*"

functions:
  storeMetadata:
    handler: handler/storeMetadataHandler.storeMetadata
    events:
    - http:
        path: /metadata
        method: post
    layers:
      - {Ref: CommonLibsLambdaLayer}
      
  fetchAllMetadata:
    handler: handler/fetchAllMetadataHandler.fetchAllMetadata
    events:
    - http:
        path: /metadata/{dicom_level}
        method: get
    layers:
      - {Ref: CommonLibsLambdaLayer} 

  fetchMetadata:
    handler: handler/fetchMetadataHandler.fetchMetadata
    events:
    - http:
        path: /metadata/{dicom_level}/{instance_UID}
        method: get
    layers:
      - {Ref: CommonLibsLambdaLayer}

  deleteMetadata:
    handler: handler/deleteMetadataHandler.deleteMetadata
    events:
    - http:
        path: /metadata/{dicom_level}/{instance_UID}
        method: delete
    layers:
      - {Ref: CommonLibsLambdaLayer}

layers:
  commonLibs:
    path: layer
    compatibleRuntimes: 
      - nodejs12.x

resources:
  Resources:
    MetaDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "sopInstanceUID"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "sopInstanceUID"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.METADATA_TABLE}
    StudyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "studyInstanceUID"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "studyInstanceUID"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.STUDY_TABLE}
    SeriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "seriesInstanceUID"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "seriesInstanceUID"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.SERIES_TABLE}