service: metadata-archive-api

frameworkVersion: '3'

custom:
  settings:
    POSTS_TABLE: metadata

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${self:custom.settings}
  region: ap-south-1
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource:
          - "*"

functions:
  storeMetadata:
    handler: metadataHandler.storeMetadata
    events:
    - http:
        path: /metadata
        method: post
        
  fetchAllMetadata:
    handler: metadataHandler.fetchAllMetadata
    events:
    - http:
        path: /metadata
        method: get

  fetchMetadata:
    handler: metadataHandler.fetchMetadata
    events:
    - http:
        path: /metadata/{meta_store_id}
        method: get

  deleteMetadata:
    handler: metadataHandler.deleteMetadata
    events:
    - http:
        path: /metadata/{meta_store_id}
        method: delete
  
resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "meta_store_id"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "meta_store_id"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.POSTS_TABLE}
